### PR TITLE
generate: send 'nil' rather than empty string to protoc generators

### LINKED ISSUE #165: generate: protoc-gen-grpc-gateway doesn't work without logtostderr parameter
When a `.gunkconfig` has a `[generate grpc-gateway]`, it will crash if it does not include a `logtostderr=true` parameter:

```sh
$ cat .gunkconfig
[generate grpc-gateway]
ken@ken-desktop:~/src/go/src/gr.id$ gunk version && gunk generate ./... -v -x
gunk v0.1.0
protoc-gen-grpc-gateway 
F0119 09:19:39.827183   16893 main.go:68] Cannot set flag 
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc0001e6500, 0xc0001f2020, 0x3b, 0x40)
	/home/ken/src/go/src/github.com/golang/glog/glog.go:769 +0xd4
github.com/golang/glog.(*loggingT).output(0x9022a0, 0xc000000003, 0xc0001f2000, 0x8e36d4, 0x7, 0x44, 0x0)
	/home/ken/src/go/src/github.com/golang/glog/glog.go:720 +0x329
github.com/golang/glog.(*loggingT).printf(0x9022a0, 0xc000000003, 0x6d9f23, 0x12, 0xc000185f18, 0x1, 0x1)
	/home/ken/src/go/src/github.com/golang/glog/glog.go:655 +0x14b
github.com/golang/glog.Fatalf(0x6d9f23, 0x12, 0xc000185f18, 0x1, 0x1)
	/home/ken/src/go/src/github.com/golang/glog/glog.go:1148 +0x67
main.main()
	/home/ken/src/go/src/github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/main.go:68 +0xb40
error: error executing "protoc-gen-grpc-gateway": exit status 255
ken@ken-desktop:~/src/go/src/gr.id$ echo "logtostderr=true" >> .gunkconfig
ken@ken-desktop:~/src/go/src/gr.id$ gunk generate ./... -v -x
protoc-gen-grpc-gateway 
github.com/brankas/grid/v1
```

Since this is likely to be one of the more used generators with Gunk, I would suggest that this parameter get injected by default for the `protoc-gen-grpc-gateway` generator.

### PR DESCRIPTION
**Pull request by vishen**
We are sending an empty string to protoc generators for the 'Parameter'.
This was causing issues with 'protoc-gen-grpc-gateway'. We now send
'nil' when there is no parameters found in the config for a generator.

Fixes #165

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -72,6 +72,25 @@ func (g Generator) OutPath(packageDir string) string {
 	return filepath.Join(g.ConfigDir, g.Out)
 }
 
+// addDefaults will add any required default values to
+// the generator.
+func (g *Generator) addDefaults() {
+	switch true {
```
Comment (jwangsadinata) [inline config/config.go]: remove `true`? I think `switch true` and `switch` are both the same thing?

Comment (vishen) [reply config/config.go]: Ah, thanks!

**Comment by vishen** [comment]
CI should be fixed now :)

File: config/config.go [hunk 2]
```diff
@@ -72,6 +72,25 @@ func (g Generator) OutPath(packageDir string) string {
...
+				foundParam = true
+				break
+			}
+		}
+		if !foundParam {
+			g.Params = append(g.Params, KeyValue{"logtostderr", "true"})
+		}
+	}
+}
+
```
Comment (mvdan) [inline config/config.go]: You can now delete this, I presume.

File: config/config.go [hunk 3]
```diff
@@ -211,6 +230,8 @@ func load(reader io.Reader) (*Config, error) {
 		if err != nil {
 			return nil, err
 		}
+		// Add any default values to the generator if required.
+		// gen.addDefaults()
```
Comment (mvdan) [inline config/config.go]: And this.

File: generate/generate.go [hunk 4]
```diff
@@ -313,7 +313,9 @@ func execError(command string, err error) error {
 }
 
 func (g *Generator) generatePlugin(req plugin.CodeGeneratorRequest, gen config.Generator) error {
-	req.Parameter = proto.String(gen.ParamString())
+	if ps := gen.ParamString(); ps != "" {
```
Comment (mvdan) [inline generate/generate.go]: please add a short comment as to why

File: generate/generate.go [hunk 5]
```diff
@@ -313,7 +313,9 @@ func execError(command string, err error) error {
...
+		req.Parameter = proto.String(gen.ParamString())
```
Comment (mvdan) [inline generate/generate.go]: reuse `ps`

File: config/config.go (hunk 2 above)
Comment (vishen) [reply config/config.go]: Oops, forgot about this. Done.

File: config/config.go (hunk 3 above)
Comment (vishen) [reply config/config.go]: Done

File: generate/generate.go (hunk 4 above)
Comment (vishen) [reply generate/generate.go]: Done.

File: generate/generate.go (hunk 5 above)
Comment (vishen) [reply generate/generate.go]: Done.
